// <auto-generated />
namespace DRS.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Bardock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bardock));
        
        string IMigrationMetadata.Id
        {
            get { return "202310140737068_Bardock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
